### ISSUE TITLE
Support for expo-sqlite

### ISSUE THREAD

**Issue by ghost** [craftzdog/pouchdb-react-native#10]
expo-sqlite works perfectly as an adapter with rxdb-pouchdb for instance but in your version we cannot specify it as an adapter.

Any way we can make this work as expo is much more modern?

**Comment by ghost** [comment]
My bad, this works fine with expo-sqlite using "react-native-sqlite" as the adapter option. 

Would be nice regardless if the expo setup option was documented for new users.

**Comment by artanisdesign** [comment]
@infosisio how did you make this work with expo-sqlite?

**Comment by ghost** [comment]
@artanisdesign 

```js
import * as SQLite from "expo-sqlite";
import SQLiteAdapterFactory from "pouchdb-adapter-react-native-sqlite";

global.Buffer = global.Buffer || require('buffer').Buffer

if (!global.btoa) {
    global.btoa = encode;
}

if (!global.atob) {
    global.atob = decode;
}

process.browser = true;

const SQLiteAdapter = SQLiteAdapterFactory(SQLite)

PouchDB
  .plugin(SQLiteAdapter)

export const ExamplePouchDB = new PouchDB('ExamplePouchDB', {adapter: 'react-native-sqlite'})
```

**Comment by artanisdesign** [comment]
Thanks for the quick response @infosisio 

yea, i got this part, i have the whole shim.js from readme

the app runs, but with a warning
`[Unhandled promise rejection: Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported]
at http://192.168.136.141:19000/index.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:518226:21 in rng
at node_modules/@craftzdog/pouchdb-core-react-native/lib/index.js:429:54 in pouchdbUtils.adapterFun$argument_1
`

still when i try to put a document into the db, nothing happens, like that promise doesnt want to resolve or reject at all.. :/

**Comment by ghost** [comment]
@artanisdesign Yeah, you need to install react-native-uuid to get rid of that error. There were a few steps involved with getting rid of a few such errors but I can't recall them off the top of my head.

**Comment by artanisdesign** [comment]
@infosisio genius, i'v been using the normal uuid package, damn :) thanks a lot mate

**Comment by Ngomana** [comment]
When using expo-sql lite, do you need to be using the expo framework or does it work on barebones react native?

**Comment by nicotroia** [comment]
> [@artanisdesign](https://github.com/artanisdesign)
> 
> import * as SQLite from "expo-sqlite";
> import SQLiteAdapterFactory from "pouchdb-adapter-react-native-sqlite";
> 
> global.Buffer = global.Buffer || require('buffer').Buffer
> 
> if (!global.btoa) {
>     global.btoa = encode;
> }
> 
> if (!global.atob) {
>     global.atob = decode;
> }
> 
> process.browser = true;
> 
> const SQLiteAdapter = SQLiteAdapterFactory(SQLite)
> 
> PouchDB
>   .plugin(SQLiteAdapter)
> 
> export const ExamplePouchDB = new PouchDB('ExamplePouchDB', {adapter: 'react-native-sqlite'})

Thanks for this. Which "pouchdb" package are you using (alongside expo-sqlite)?

I'm trying
"pouchdb": "^9.0.0",
"pouchdb-react-native": "^6.4.1",
"@craftzdog/pouchdb-core-react-native": "^7.2.2",

Currently stuck on `const SQLiteAdapter = SQLiteAdapterFactory(SQLite);` as it says `PouchDB.adapter is not a function`
