### ISSUE TITLE
https://registry.npmjs.org/@craftzdog%2fpouchdb-collate-react-native: Not found

### ISSUE THREAD

**Issue by umagon** [craftzdog/pouchdb-react-native#14]
### Issue
When following the guide in the `README.md`, there is a step that states:
```
yarn add @craftzdog/pouchdb-collate-react-native
```
However, an error is raised:
```bash
$ yarn add @craftzdog/pouchdb-collate-react-native
yarn add v1.22.19
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/@craftzdog%2fpouchdb-collate-react-native: Not found".  
info If you think this is a bug, please open a bug report with the information provided in "E:\\Software\\Repositorios\\lax-calendar\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

It seems the registry does not host the package anymore. Maybe a re-upload is enough?

### Info
- Environment: Node.js
- Platform: React-Native/Android
- Adapter: WebSQLite
- Server: PouchDB/WebSQL/SQLite

**Comment by BlancaCC** [comment]
I get the same error  the log is 

```
Arguments: 
  /opt/homebrew/Cellar/node/18.7.0/bin/node /opt/homebrew/bin/yarn add @craftzdog/pouchdb-collate-react-native

Yarn version: 
  1.22.19

Node version: 
  18.7.0

Platform: 
  darwin arm64
```

**Comment by MarcelLZ** [comment]
Same error here!

**Comment by Productivix** [comment]
same error , attached is the debug file of yarn - hope will help to solve - obviously a `bug `
[yarn-error.log](https://github.com/craftzdog/pouchdb-react-native/files/9876060/yarn-error.log)

**Comment by Productivix** [comment]
see : https://github.com/digpak/pouchdb-rn-collate

**Comment by Productivix** [comment]
yarn add pouchdb-collate
it replaced the missing @craftzdog/pouchdb-collate-react-native
and maybe in babel.config.js add : 
`plugins: [
    [
      'module-resolver',
      {
        alias: {
          '@craftzdog/pouchdb-collate-react-native': 'pouchdb-collate',
        },
      },
    ],
  ],`

**Comment by craftzdog** [comment]
ahh my bad, made the package public.
