### ISSUE TITLE
Get this back into PouchDB?

### ISSUE THREAD

**Issue by deeuu** [craftzdog/pouchdb-react-native#2]
Hey,

Great work on getting PouchDB working with RN.

Are you considering setting up a PR with the [upstream repo](https://github.com/pouchdb/pouchdb)?

It would be nice to work with the latest pouchdb releases and the associated typescript definitions...

Thanks again

**Comment by leonid-shevtsov** [comment]
Some implementation ideas:

- You can do a [runtime check for React Native](https://stackoverflow.com/questions/39468022/how-do-i-know-if-my-code-is-running-as-react-native) (and then enable these patches).
- Or maybe add some `storeAttachmentsInBase64` flag to the PouchDB store options and either have it auto-enabled upon detecting React Native, or explicitly enabled when constructing the store - the latter seems to be the least invasive option.

**Comment by craftzdog** [comment]
Yeah it would be great but I don't have time right now.
The best scenario would be that RN eventually supports `readAsArrayBuffer`.
Found an interesting post: https://github.com/facebook/react-native/issues/21209#issuecomment-495294672
