### ISSUE TITLE
Rebase off PouchDB 7.1.1

### ISSUE THREAD

**Issue by leonid-shevtsov** [craftzdog/pouchdb-react-native#3]
Hi,

#2 is ideal, but given the release cadence of PouchDB, it's more expedient to bump the version used in this fork:

PouchDB 7.1.1 has been [released](https://pouchdb.com/2019/06/13/pouchdb-7.1.1.html) on June 13, 2019 with some valuable dependency upgrades.

**Comment by craftzdog** [comment]
Done.
https://dev.to/craftzdog/created-pouchdb-7-for-react-native-23g6
