### ISSUE TITLE
Stops replicating in release on 64-bit android devices

### ISSUE THREAD

**Issue by greenais** [craftzdog/pouchdb-react-native#4]
### Issue
Works like a charm on 32-bit devices, thanks for your inestimable efforts!
But when it comes to 64-bit android in release apk on real devices replication stops to work with uninformative error:

```
{ [Error]
10-19 08:55:39.157 22836 22855 I ReactNativeJS:   line: 132,
10-19 08:55:39.157 22836 22855 I ReactNativeJS:   column: 7285,
10-19 08:55:39.157 22836 22855 I ReactNativeJS:   sourceURL: 'index.android.bundle',
10-19 08:55:39.157 22836 22855 I ReactNativeJS:   result: 
10-19 08:55:39.157 22836 22855 I ReactNativeJS:    { ok: false,
10-19 08:55:39.157 22836 22855 I ReactNativeJS:      start_time: '2019-10-19T05:55:38.997Z',
10-19 08:55:39.157 22836 22855 I ReactNativeJS:      docs_read: 0,
10-19 08:55:39.157 22836 22855 I ReactNativeJS:      docs_written: 0,
10-19 08:55:39.157 22836 22855 I ReactNativeJS:      doc_write_failures: 0,
10-19 08:55:39.157 22836 22855 I ReactNativeJS:      errors: [],
10-19 08:55:39.157 22836 22855 I ReactNativeJS:      status: 'aborting',
10-19 08:55:39.157 22836 22855 I ReactNativeJS:      end_time: '2019-10-19T05:55:39.155Z',
10-19 08:55:39.157 22836 22855 I ReactNativeJS:      last_seq: 0 } }
```
 Tried several devices and both platforms - armeabi-v7a and arm64-v8a, all the same.
Meanwhile in debug mode on the same devices attached via USB  everything works, same code.

Any thoughts where root of the issue may be?

### Info
- Environment: 
    "@craftzdog/pouchdb-core-react-native": "7.0.0",
    "@craftzdog/pouchdb-replication-react-native": "7.0.0",
    "pouchdb-adapter-http": "7.1.1",
    "pouchdb-adapter-react-native-sqlite": "2.0.0",
    "pouchdb-authentication": "1.1.3",
    "pouchdb-mapreduce": "7.1.1",
    "react-native": "0.61.2",

### Reproduce
```
let remoteDB = new PouchDB(serverURL + dbName, cdbOptions);
      localDB.replicate.from(remoteDB, {
        doc_ids: docList
      })
```

Thank you in advance.
I was ready to release my app but then bumped into this really blocking 64-bit issue(
How it could be possible that SAME code works in debug but not in release on SAME device?
Mystic.

**Comment by craftzdog** [comment]
My [essential phone is 64bit](https://www.essential.com/phone) and it's working fine.
I have a production app and it works as well.

**Comment by greenais** [comment]
Thank you for a bit of light of hope - it's already almost two weeks of googling-trying-failing and beating my head against the wall.
I tried release on Redmi 8, Honor and couple of other quite modern devices - same result(
My suspicion is around something broken in RN release build process, otherwise I can't explain why it works in debug mode.
Which RN version do you use in your working app? Built on Mac, Linux, win?
If it's appropriate - could you please share relevant parts of your app/build gradle?
I really don't know where to look for any reasons for such mystique.
Thank you in advance.

**Comment by craftzdog** [comment]
Maybe you need to install "@craftzdog/pouchdb-binary-utils-react-native".
I totally forgot about this package but I use it in my project.
My RN is 0.60.5.
If it still doesn't work, you have to inspect the cause of the error by adding `console.log` in the modules.

**Comment by greenais** [comment]
Thank you very much for your tip, I'll try it tonight and come back with results.
How should I use this pouchdb-binary-utils-react-native in the project, just import it early like I do with  btoa/atob polifills?

Which modules woul you recommend to start with to inspect?
@craftzdog/pouchdb-replication-react-native, pouchdb-authentication?

**Comment by craftzdog** [comment]
Use `babel-plugin-module-resolver` to replace `pouchdb-binary-utils` with `@craftzdog/pouchdb-binary-utils-react-native` like so:

`babel.config.js`:

```js
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        alias: {
          'pouchdb-binary-utils': '@craftzdog/pouchdb-binary-utils-react-native'
        }
      }
    ]
  ]
}
```

I don't have time to tell you how to inspect, but you have to be able to understand what's going on in PouchDB basically because this module is just a hack of it, no official support.

**Comment by greenais** [comment]
Tried pouchdb-binary-utils-react-native, same result as without it.
Will keep investigating modules and give a shot on Linux building. RN team sometimes leave minor annoying bugs on win platform, as they love Macs..
.

**Comment by craftzdog** [comment]
Does it work without remote debugging?

**Comment by greenais** [comment]
No, unfortunately.
Tried 
- on Windows and Linux
- using default JSC and brand new Hermes (it reduces apk, btw, from 11MB to 8, a nice surprise, I'll stay on it)
- with and without your hacked binary-utils
- on most recent RN 0.61.2 and downgrded to your working 0.60.5
all the same:
32 bit release works, 64 bit - doesn't. Providing same uninformative error as above but now with one additional string
`jsEngine: 'hermes',`

I'm really out of ideas why PDB may behave so differently on 64-bit platform in my case while you confirm that it really works in prod. 
Same libs, same versions - only code surely differs. That's last resort I can guess - my code leads to such a mystic edge case on 64-bit.  
The only option to debug release build is adb logcat, am I right?

**Comment by greenais** [comment]
After updating metro-react-native-babel-preset to the most recent version 0.56.3 (along with your new react-native-sqlite-2) release replication is broken even on 32-bit devices - with same symptoms:
- on js side error as above (with status "aborting")
- couhcdb log doesn't show any requests from client as they didn't happened at all

Debug on emulator and device works.

Device logcat is totally uninformative as well:

```
10-27 01:30:49.500 22902 22949 E unknown:ReactNative: console.error: " %%%%%%%%%%%>>> _checkCDB ERR: ", {"reason":"CC_not_found","inet":true,"cdb":false}, stack:
10-27 01:30:49.500 22902 22949 E unknown:ReactNative: c@100:482
10-27 01:30:49.500 22902 22949 E unknown:ReactNative: f@98:363
10-27 01:30:49.500 22902 22949 E unknown:ReactNative: c@97:239
10-27 01:30:49.500 22902 22949 E unknown:ReactNative: f@97:1241
10-27 01:30:49.500 22902 22949 E unknown:ReactNative: <unknown>@390:9993
10-27 01:30:49.500 22902 22949 E unknown:ReactNative: f@108:155
10-27 01:30:49.500 22902 22949 E unknown:ReactNative: <unknown>@108:882
10-27 01:30:49.500 22902 22949 E unknown:ReactNative: y@114:661
10-27 01:30:49.500 22902 22949 E unknown:ReactNative: C@114:1025
10-27 01:30:49.500 22902 22949 E unknown:ReactNative: callImmediates@114:3100
10-27 01:30:49.500 22902 22949 E unknown:ReactNative: callImmediates@-1
10-27 01:30:49.500 22902 22949 E unknown:ReactNative: value@26:3247
10-27 01:30:49.500 22902 22949 E unknown:ReactNative: <unknown>@26:1283
10-27 01:30:49.500 22902 22949 E unknown:ReactNative: value@26:2939
10-27 01:30:49.500 22902 22949 E unknown:ReactNative: value@26:1253
10-27 01:30:49.500 22902 22949 E unknown:ReactNative: value@-1
10-27 01:30:49.500 22902 22949 E unknown:ReactNative: value@-1
```

Really it seems that root of the problem is V8 (used in debug) misalignment compared to JSC. 
The question is what we can do with that but rewriting pouchdb for JSC? 
I'm completely lost...

**Comment by greenais** [comment]
@craftzdog could you please share your working "devDependencies" section of package.json?
I found out that RN 0.60.5 init brings "latest and greatest" metro-react-native-babel-preset 0.56.3 which I suspect to do evil job in release compilation - now even for 32-bit

**Comment by craftzdog** [comment]
I'm on vacation right now.
Here:

```json
"devDependencies": {
  "@babel/core": "^7.5.5",
  "@babel/runtime": "^7.5.5",
  "babel-eslint": "^10.0.3",
  "babel-jest": "^24.8.0",
  "babel-plugin-module-resolver": "^3.2.0",
  "eslint": "^6.3.0",
  "eslint-config-prettier": "^6.3.0",
  "eslint-plugin-flowtype": "^4.3.0",
  "eslint-plugin-prettier": "^3.1.0",
  "eslint-plugin-react": "^7.14.3",
  "flow-bin": "^0.98.0",
  "jest": "^24.8.0",
  "metro-react-native-babel-preset": "^0.56.0",
  "prettier": "^1.18.2",
  "react-test-renderer": "16.8.6",
  "redux-logger": "^3.0.6"
},
```

```
npm ls | grep metro-react-native-babel-preset
├─┬ metro-react-native-babel-preset@0.56.0
│ │ │ ├─┬ metro-react-native-babel-preset@0.54.1
│ │ └─┬ metro-react-native-babel-preset@0.54.1
```

**Comment by greenais** [comment]
Oh, sorry to disturb. 
Thank you!

**Comment by greenais** [comment]
After adding some error logging to pouchdb-replication-react-native I found out that there is nothing wrong with pouchdb itself - Android is just silently blocking requests to non-https endpoints (which my app uses by now) since API28. Damn, RN guys even removed topic regarding this from docs(
Added => android/app/src/main/AndroidManifest.xml
```
...
<application>
...
  android:usesCleartextTraffic="true"
>
```
and problem gone even on RN 0.61.2.

Thank you very much for your support, without it I couldn't figure out what is going on, really

**Comment by craftzdog** [comment]
Good to hear that!
Cheers
